### ISSUE TITLE
Memo AI Editing Bug

### ISSUE THREAD

**Issue by Dennis168968** [Makememo/MemoAI#216]
![MemoC1](https://github.com/Makememo/MemoAI/assets/126966885/9db69417-dcc3-4871-958b-9d439f64b3d0)
![MemoC2](https://github.com/Makememo/MemoAI/assets/126966885/91eb1d9c-d323-4c8d-a314-9ed36e9ffba9)
**Describe the bug**
Bug 1- Suggest to not run the "auto save" feature while editing. Also, the mouse courser should not be moved to the final.
1. Step 1 -- Input the voice and generate the Chinese traditional sentence.
2. Step 2 -- Clicking the middle sentence character and editing, the system will run "save" automatically and mouse courser to final.

Bug 2 - The voice playing and sentence display timing is not match (seems slow)
1. Step 1 -- Input the voice and generate the Chinese traditional sentence.
2. Step 2 - Play the voice and see the sentence display.

Bug 3 - The voice play should stay the stop status while editing the character.
1. Step 1 -- Input the voice and generate the Chinese traditional sentence.
2. Step 2 - Click the subtitle editing
3. step 3 - Select any sentence
4. step 4 - Click every sentence middle character. The voice playing will be run automatically

**Comment by Makememo** [comment]
It has been solved. Https://github.com/Makememo/MemoAI/releases/tag/v1.2.1, please download it here.

**Comment by Dennis168968** [comment]
The bug 1 solved. But, the bug 2 and 3 are still problems and not solved yet.

Bug 2 - The voice playing and sentence display timing do not match (seems slow)
Step 1 -- Input the voice and generate the Chinese traditional sentence.
Step 2 - Play the voice and see the sentence display (The middle block; the right part OK)
Bug 3 - The voice play should stay at the stop status while editing the character.
![MemoC1](https://github.com/Makememo/MemoAI/assets/126966885/fb9b30e9-179e-4101-8f8e-5336c61316ce)
![MemoC2](https://github.com/Makememo/MemoAI/assets/126966885/d201da68-a579-42a3-86a5-a0c3be7fbb53)

Bug 3 - The voice should not be played automatically while clicking the middle sentence character.
Step 1 -- Input the voice and generate the Chinese traditional sentence.
Step 2 - Click the subtitle editing feature
step 3 - Select any subtitle sentence
step 4 - Click every sentence's middle character, the voice will play automatically
